spring:
  datasource:
    url: jdbc:mysql://localhost:3306/booking_oauth2?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: workbench_user
    password: 090994ss

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true


  security:
    oauth2:
      client:
        registration:
          github:
            client-id: Ov23liyvBOM1hXJF1qoe
            client-secret: 1c01b0c3f83b5c410707033cec47e50245ce5718
            scope:
              - read:user
              - user:email
              - public_repo