spring:
  datasource:
    url: jdbc:mysql://localhost:3306/MeetingRoom-BookingSystem?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: workbench_user
    password: 090994ss

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true

